export const MASSIVE_CONNECT_OPTIONS = 'MASSIVE_CONNECT_OPTIONS';
export const MASSIVE_CONFIG_OPTIONS = 'MASSIVE_CONFIG_OPTIONS';
export const MASSIVE_DRIVER_OPTIONS = 'MASSIVE_DRIVER_OPTIONS';
export const MASSIVE_CONNECTION = 'MASSIVE_CONNECTION';
